services:
  prod-client:
    container_name: todo-for-mindbox-prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "${DOCKER_PORT_PROD_HTTP:-3000}:80"
      - "${DOCKER_PORT_PROD_HTTPS:-3001}:443"
    volumes:
      - ./docker/prod/nginx/default.conf:/etc/nginx/nginx.conf:ro